### ISSUE TITLE
请问，你准备了m3u的文件后，在盒子里面用什么app播放这个文件呢？

### ISSUE THREAD

**Issue by jufei** [GaryOAO/IPTV-CN#1]
谢谢。

**Comment by GaryOAO** [comment]
很久没上Github了，刚刚看到你的问题。之前使用的是Perfecr Player，很好用的一个软件。最后发现对于老年人来说这样的操作还是过于复杂，而且不同网络下串流信息维护也过于繁琐，会出现一些问题。比如说在移动网络下正常播放的在联通网络下播放就很不正常，而且某个流很容易就失效了。所以说最后还是让老人用了电视家3.0。
